# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemType', models.CharField(choices=[('PAGE', 'Page'), ('CAT', 'Training Category')], max_length=15)),
                ('iconRef', models.CharField(max_length=25, verbose_name='Icon Code')),
                ('iconName', models.CharField(max_length=25)),
                ('weight', models.IntegerField()),
                ('primary', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('viewName', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grad_year', models.IntegerField(blank=True, null=True)),
                ('committee', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(choices=[('GRAD', 'Graduated'), ('STU', 'Student'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Training_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('trainee', models.ManyToManyField(related_name='trainee', to='nt_training.Person')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainer', to='nt_training.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Training_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingId', models.DecimalField(decimal_places=2, max_digits=4, unique=True)),
                ('trainingTitle', models.CharField(max_length=50)),
                ('description', models.TextField(default='Provide a useful description')),
                ('safety', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nt_training.Icon')),
            ],
        ),
        migrations.AddField(
            model_name='training_session',
            name='trainingId',
            field=models.ManyToManyField(to='nt_training.Training_Spec'),
        ),
    ]
