# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nt_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_trainer',
            field=models.BooleanField(default=False, help_text='Tick if this person trains others.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
