# Generated by Django 2.2 on 2019-04-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nt_training', '0002_auto_20181217_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training_session',
            options={'verbose_name': 'Training Session'},
        ),
        migrations.AlterModelOptions(
            name='training_spec',
            options={'verbose_name': 'Training Specification'},
        ),
        migrations.AlterField(
            model_name='icon',
            name='iconName',
            field=models.CharField(max_length=25, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='iconRef',
            field=models.CharField(help_text='From <a href="https://fontawesome.com/icons?d=gallery&m=free">Font Awesome 5</a>. Example: <code>fas fa-user</code>.', max_length=25, verbose_name='Icon Code'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='viewName',
            field=models.CharField(blank=True, default=None, help_text='For pages only.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='training_spec',
            name='category',
            field=models.ForeignKey(limit_choices_to={'itemType': 'CAT'}, on_delete=django.db.models.deletion.DO_NOTHING, to='nt_training.Icon'),
        ),
        migrations.AlterField(
            model_name='training_spec',
            name='safety',
            field=models.BooleanField(default=False, help_text='Tick if training point has a health and safety element, or requires a period of supervision before signing off.'),
        ),
        migrations.AlterField(
            model_name='training_spec',
            name='trainingTitle',
            field=models.CharField(max_length=50, verbose_name='Training Title'),
        ),
    ]
