# Generated by Django 2.2 on 2019-05-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nt_training', '0003_auto_20190422_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Department Name')),
                ('person', models.CharField(help_text='Person in charge of the department', max_length=50)),
                ('email', models.EmailField(help_text='Email address of the person in charge', max_length=254)),
                ('weight', models.IntegerField(unique=True)),
                ('department_icon', models.CharField(default='fa fa-', help_text='From <a href="https://fontawesome.com/icons?d=gallery&m=free">Font Awesome 5</a>. Example: <code>fas fa-user</code>.', max_length=25, verbose_name='Icon Code')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ['itemType', 'weight']},
        ),
        migrations.AlterModelOptions(
            name='training_spec',
            options={'ordering': ['category', 'trainingId'], 'verbose_name': 'Training Specification'},
        ),
        migrations.AlterField(
            model_name='icon',
            name='primary',
            field=models.BooleanField(default=False, help_text='For pages only. Tick to appear on the homepage.'),
        ),
        migrations.AddField(
            model_name='icon',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Department this category belongs to. If you're using departments, you <strong>must</strong> set this for the category to appear.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='nt_training.Department'),
        ),
    ]
