# Generated by Django 2.2.4 on 2019-08-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nt_training', '0006_auto_20190827_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_page',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
