# Generated by Django 2.2.4 on 2019-08-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nt_training', '0007_site_page_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_page',
            options={'verbose_name': 'Site Page'},
        ),
    ]
