# Generated by Django 2.2.4 on 2019-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nt_training', '0008_auto_20190827_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_page',
            name='iconRef',
            field=models.CharField(default='fa', help_text='From <a href="https://fontawesome.com/icons?d=gallery&m=free">Font Awesome 5</a>. Example: <code>fas fa-user</code>.', max_length=25, verbose_name='Icon Code'),
            preserve_default=False,
        ),
    ]
