# Generated by Django 2.2.4 on 2019-08-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nt_training', '0009_site_page_iconref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_page',
            options={'ordering': ['weight'], 'verbose_name': 'Site Page'},
        ),
    ]
